listened_keyboard_event_file: /dev/input/event13
combination_trigger_key:
  event_code: KEY_PROG1 # symbolic event code
  keycode: 156          # numeric code
  modifier_name: mod3   # null if not a modifier
